---

- name: Block-in-file with leading TAB
  blockinfile:
    path: "{{ test_conf }}"
    insertbefore: '^};$'
    marker: "\t// {mark} ANSIBLE MANAGED BLOCK"
    block: |
      	extra line with leading TAB;
      	another line with leading TAB;
